@extends('layouts.frontend')

@section('content')

<section class="col-md-12 sp-ch-banner-section">
    <div class="col-12 sp-banner-image">
        <img src="{{ asset('frontend/images/challanges-banner.jpg') }}" alt="Challenges-Banner"/>
    </div>
    <div class="container">
        <div class="col-12 sp-banner-caption">
            <span class="display-2"> Terms of Service </span>       
        </div>
    </div>
</section>


<section class="col-md-12" style=" float: left;width: 100%;padding: 0;">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-12 col-md-offset-2">
                <p>Terms of Service</p>
                <p>Date of Last Revision: October 1, 2019</p>
                <p>Introduction</p>
                <p>Acceptance. By using the Website or Services in any manner, you are bound by these Terms of Service, as well as the Incorporated Terms identified below (collectively, the “Terms”). If you do not agree to the Terms, then do not use the Website or Services. If you are accepting these Terms on behalf of a company, organization, government, or other legal entity, you represent and warrant that (a) you are authorized to do so, (b) the entity agrees to be legally bound by the Terms, and (c) neither you nor the entity are barred from using the Services or accepting the Terms under the laws of the applicable jurisdiction.</p>
                <p>Scope. These Terms govern your use of the Website and the Services. Except as otherwise specified, these Terms do not apply to Third-Party Products, which are governed by their own terms of service.</p>
                <p>Incorporated Terms. The following policies, guidelines, and agreements (“Incorporated Terms”) are hereby incorporated into, and form an integral part of, the Terms to which you are agreeing to be bound:</p>
                <p>Privacy Policy</p>
                <p>Acceptable Use Policy</p>
                <p>API Terms</p>
                <p>Infringing Materials Protocol</p>
                <p>Mobile App Terms</p>
                <p>Contracting Entity. “Sprowtt Launch Pad Inc.” means the Sprowtt Launch Pad Inc. entity with which you are entering into these Terms. If you have previously entered into an agreement with a Sprowtt Launch Pad Inc. entity, then “Sprowtt Launch Pad Inc.” means that entity. If you have not previously entered into an agreement with a Sprowtt Launch Pad Inc. entity, then “Sprowtt Launch Pad Inc.” means the entity identified in the following table:</p>
                <p>United States   Sprowtt Launch Pad Inc, a Florida  Corporation in the United States </p>
                <p>Certain Definitions.</p>
                <p>“Order Form” or “Order” means one or more Sprowtt Launch Pad Inc. order forms executed by the parties for the purchase of Services and that reference these Terms.</p>
                <p>“Services” means all Sprowtt Launch Pad Inc. products, services, and materials located on or accessible through the Website or otherwise described.</p>
                <p>“Third-Party Products” means any third-party information, website, product, service, or materials referenced in, accessible through, or provided in connection with, the Website or Services.</p>
                <p>“Website” means the Sprowtt Launch Pad Inc. website located at www.Sprowtt Launch Pad Inc..com (including all associated internet country codes), together with all Sprowtt Launch Pad Inc. websites and webpages accessible there, and the Account control panel.</p>


                <p>Eligibility.</p>
                <p>Minimum Age. The Services and Website are available only to persons who are the age of majority and can form legally binding contracts under applicable law. Without limiting the foregoing, the Services and Website are not intended to be used by individuals under the age of 18. If you do not qualify, please do not use the Services or access the Website.</p>
                <p>Registration. In order to use the Services, you must establish a Services account (“Account”) by registering with Sprowtt Launch Pad Inc. You may be required to submit a valid means of identification for which you are authorized to participate as Student of a university or known resident of the united states. You will provide true, accurate, current, and complete information when registering for an Account and will update the information as necessary to keep your Account and payment information current. As part of the registration process, you will provide Sprowtt Launch Pad Inc. with a username and password for your Account (together “Account Credentials”). Sprowtt Launch Pad Inc. reserves the right to refuse registration of, or cancel, accounts it deems inappropriate.</p>


                <p>Security.</p>
                <p>Generally. You are responsible for maintaining the security of your Account Credentials and for all Services, accessed, or otherwise used in connection with your Account Credentials and all actions taken in association therewith. You will not share your Account Credentials with any third party.</p>
                <p>Sprowtt Launch Pad Inc. is responsible for the security of persons data to the extent that Sprowtt Launch Pad Inc. has control of that data. To that end, Sprowtt Launch Pad Inc. undertakes regular assessments consistent with the Data Security Standards.</p>


                <p>Use Restrictions. This is an agreement for Services, and you are not granted a license to any software by these Terms. You will not, directly or indirectly: reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, or algorithms of or included in the Services or any software, documentation or data related to the Services (“Software”); modify, translate or create derivative works based on the Services or any Software; or copy (except for archival purposes), distribute, pledge, assign or otherwise transfer or encumber rights to the Services or any Software; use the Services or any Software for timesharing or service bureau purposes or otherwise for the benefit of a third party; or remove any proprietary notices or labels.</p>


                <p>Intellectual Property.</p>
                <p>User Content.</p>
                <p>License. We do not claim any intellectual property rights over the content you provide to Sprowtt Launch Pad Inc. All of your content remains yours. When providing content using the Services (directly or indirectly), you grant us a non-exclusive, worldwide, royalty-free, sublicensable (through multiple tiers) right to exercise any and all copyright, trademark, patent, publicity, moral, database, and/or other intellectual property rights (collectively, "IP Rights") you have in that content or associated with your project in connection with our provision of the Services, in any media known now or developed in the future.</p>
                <p>Representations and Warranties. You represent and warrant that, for all such content you provide, you own or otherwise control all necessary rights to do so and to meet your obligations under these Terms. You represent and warrant that such content is accurate. You represent and warrant that use of any such content (including derivative works) by us, our users, or others in contract with us, and in compliance with these Terms, does not and will not infringe any IP Rights of any third party. Sprowtt Launch Pad Inc. takes no responsibility and assumes no liability for any content provided by you or any third party.</p>
                <p>Name and Marks. Sprowtt Launch Pad Inc. shall have the non-exclusive right and license to use the names, trademarks, service marks and logos associated with your store(s) to promote the Services.</p>
                <p>Sprowtt Launch Pad Inc. Content.</p>
                <p>Restrictions. All rights not expressly granted by Sprowtt Launch Pad Inc. to you in these Terms are hereby reserved by Sprowtt Launch Pad Inc. There are no implied rights. You may not use, imitate, or copy, in whole or in part, any Sprowtt Launch Pad Inc. trademark, service mark, trade dress, logo, or other branding (collectively, “Marks”) without, in each instance, Sprowtt Launch Pad Inc.’s prior written consent, in Sprowtt Launch Pad Inc.’s discretion. All permitted use of Sprowtt Launch Pad Inc.’s Marks will inure to the benefit of Sprowtt Launch Pad Inc.</p>
                <p>Ownership. As between the parties, the Website and Services, including, without limitation, any and all APIs, Software, documentation, images, video, content, logos, page headers, custom graphics, design and user interface elements, scripts, and other materials contained therein or provided in connection therewith, and all modifications, enhancements, and updates thereto, as well as all IP Rights associated with any of these materials (collectively, "Sprowtt Launch Pad Inc. IP") are owned by Sprowtt Launch Pad Inc. and/or its third party sponsors, partners, and suppliers. You have no right or license in or to the Sprowtt Launch Pad Inc. IP other than the right to use the Services, in compliance with the Terms, during the applicable subscription period.  The Participation in the site or on Team or project is no guarantee of funding or placement of offering of capital with a Sprowtt Inc or Sprowtt Crowdfunding or affiliated company to Sprowtt Inc.  There is no assurances of success or funding of capital through Sprowtt or its affiliates this site does not have a promotional agreement with Sprowtt crowdfunding a regulated entity by the securities and exchange commission. This site does promote capital formation of any type and does not allow for promotion of securities. Any registered user who promotes securities related to a project or Technology Transfer project will be removed from the sites membership and registration will be removed. </p>
                <p>Feedback. You may provide Sprowtt Launch Pad Inc. with ideas, opinions, recommendations, feedback, or advice in connection with your use of the Services (collectively, "Feedback"). If you submit Feedback to Sprowtt Launch Pad Inc., you hereby grant Sprowtt Launch Pad Inc. an irrevocable, perpetual, transferable, non-exclusive, fully-paid-up, royalty-free, worldwide license (sublicensable through multiple tiers) to: (a) use, copy, distribute, reproduce, modify, create derivative works of, adapt, publish, translate, publicly perform, and publicly display such Feedback (or any modification thereto), in whole or in part, in any format, medium or application now known or later developed; and (b) use, and permit others to use, Feedback in any manner and for any purpose (including, without limitation, commercial purposes) that Sprowtt Launch Pad Inc. deems appropriate in its discretion (including, without limitation, incorporating Feedback, in whole or in part, into any technology, product or service).</p>


                <p>Indemnification.</p>
                <p>Indemnification. You will defend, indemnify, and hold Sprowtt Launch Pad Inc. and its suppliers and affiliates, and the respective directors, officers, employees and agents of each, harmless from and against any and all claims, losses, damages, liabilities and costs (including, without limitation, reasonable attorneys’ fees and court costs) arising out of or relating to your breach of any of these Terms or use by you or any third party (authorized, permitted or enabled by you) of the Services, except to the extent the foregoing directly result from Sprowtt Launch Pad Inc.’s own gross negligence or willful misconduct. Sprowtt Launch Pad Inc. reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you. This Indemnification Section will survive any termination or expiration or these Terms.</p>


                <p>Discussion Areas.</p>
                <p>No Warranty. Sprowtt Launch Pad Inc. makes no representations or warranties with respect to any forums, blogs, private messages, emails, or other electronic discussion mediums made available through or in connection with the Services (collectively, "Discussion Areas") or with respect to any information or materials contained in the Discussion Areas. Your use of, or reliance upon, any such information or materials is at your sole risk.</p>
                <p>Your Postings. All information, content, or materials you post to a Discussion Area must comply with the Acceptable Use Policy. Sprowtt Launch Pad Inc. will have no obligation to monitor the Discussion Areas but may do so at its discretion and may delete, move, or edit any information or materials in the Discussion Areas.</p>


                <p>Arbitration Agreement and Class Action Waiver.</p>
                <p>Purpose. This Arbitration Agreement and Class Action Waiver (“Arbitration Agreement”) facilitates the prompt and efficient resolution of any disputes that may arise between you and Sprowtt Launch Pad Inc.. For the purpose of this Arbitration Agreement, “Sprowtt Launch Pad Inc.” means Sprowtt Launch Pad Inc., Inc., a Texas corporation, and each of its parents, subsidiaries, and affiliated companies, and each of their respective officers, directors, employees, and agents. This Arbitration Agreement applies to these Terms and any other agreement you may have with Sprowtt Launch Pad Inc..</p>
                <p>Arbitration is a form of private dispute resolution in which parties to a contract agree to submit their disputes and potential disputes to a neutral third person (called an arbitrator) for a binding decision, instead of having such dispute(s) decided in a lawsuit, in court, by a judge or jury trial. You have the right to opt-out of this Arbitration Agreement (as explained below), which means you would retain your right to litigate your disputes in a court, either before a judge or jury.</p>
                <p>Please read this Arbitration Agreement carefully. It provides that all disputes between you and Sprowtt Launch Pad Inc. will be resolved by binding arbitration. Arbitration replaces the right to go to court. In the absence of this Arbitration Agreement, you may otherwise have a right or opportunity to bring claims in a court, before a judge or jury, and/or to participate in or be represented in a case filed in court by others (including, but not limited to, class actions). Entering into this Arbitration Agreement constitutes a waiver of your right to litigate claims in court and all opportunity to be heard by a judge or jury. There is no judge or jury in arbitration, and court review of an arbitration award is limited. The arbitrator must follow this Arbitration Agreement and can award the same damages and relief as a court (including attorney’s fees, if otherwise authorized by applicable law).</p>
                <p>The term “Dispute” means any dispute, claim, or controversy between you and Sprowtt Launch Pad Inc. regarding any aspect of your relationship with Sprowtt Launch Pad Inc., whether based in contract, statute, regulation, ordinance, tort (including, but not limited to, fraud, misrepresentation, fraudulent inducement, negligence, gross negligence or reckless behavior), or any other legal or equitable theory, and includes the validity, enforceability or scope of this Arbitration Agreement (with the exception of the enforceability of the Class Action Waiver clause below). “Dispute” is to be given the broadest possible meaning that will be enforced.</p>
                <p>WE EACH AGREE THAT, EXCEPT AS PROVIDED BELOW, ANY AND ALL DISPUTES, AS DEFINED ABOVE, WHETHER PRESENTLY IN EXISTENCE OR BASED ON ACTS OR OMISSIONS IN THE PAST OR IN THE FUTURE, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION RATHER THAN IN COURT IN ACCORDANCE WITH THIS ARBITRATION AGREEMENT.</p>
                <p>Pre-Arbitration Dispute Resolution. For all Disputes you must first give Sprowtt Launch Pad Inc. an opportunity to resolve the Dispute. You must commence this process by mailing written notification to:</p>
                <p>Sprowtt Launch Pad Inc.</p>
                <p>3030 N Rocky Point Dr W Suite 150</p>
                <p>Tampa, FL 33607</p>

                <p>That written notification must include (1) your name, (2) your address, (3) a written description of the Dispute, and (4) a description of the specific relief you seek. If Sprowtt Launch Pad Inc. does not resolve the Dispute to your satisfaction within 45 days after it receives your written notification, you may pursue your Dispute in arbitration.</p>
                <p>Arbitration Procedures. If this Arbitration Agreement applies and the Dispute is not resolved as provided above (“Pre-Arbitration Claim Resolution”) either you or Sprowtt Launch Pad Inc. may initiate arbitration proceedings. The American Arbitration Association (“AAA”), www.adr.org, or JAMS, www.jamsadr.com, will arbitrate all Disputes, and the arbitration will be conducted before a single arbitrator. The arbitration will be commenced as an individual arbitration and will in no event be commenced as a representative or class arbitration. All issues will shall be for the arbitrator to decide, including the scope of this Arbitration Agreement.</p>
                <p>For arbitration before the AAA, for Disputes of less than $75,000, the AAA’s Supplementary Procedures for Consumer-Related Disputes will apply; for Disputes involving $75,000 or more, the AAA’s Commercial Arbitration Rules will apply. In either instance, the AAA’s Optional Rules For Emergency Measures Of Protection will shall apply. The AAA rules are available at www.adr.org or by calling 1-800-778-7879. For arbitration before JAMS, the JAMS Comprehensive Arbitration Rules & Procedures and the JAMS Recommended Arbitration Discovery Protocols For Domestic, Commercial Cases will apply. The JAMS rules are available at www.jamsadr.com or by calling 1-800-352-5267. This Arbitration Agreement governs in the event it conflicts with the applicable arbitration rules. Under no circumstances will class action, representative action, or collective action procedures or rules apply to the arbitration.</p>
                <p>Because your contract with Sprowtt Launch Pad Inc., these Terms, and this Arbitration Agreement concern interstate commerce, the Federal Arbitration Act (“FAA”) governs the arbitrability of all Disputes. However, the arbitrator will apply applicable substantive law consistent with the FAA and the applicable statute of limitations or condition precedent to suit.</p>
                <p>Exclusions from Arbitration/Right to Opt Out. Notwithstanding the above, you or Sprowtt Launch Pad Inc. may choose to pursue a Dispute in court and not by arbitration if (a) the Dispute qualifies, it may be initiated in small claims court; or (b) YOU OPT-OUT OF THESE ARBITRATION PROCEDURES WITHIN 30 DAYS FROM THE DATE THAT YOU FIRST CONSENT TO THIS AGREEMENT (the “Opt-Out Deadline”). You may opt out of this Provision by mailing written notification to</p>
                <p>Sprowtt Launch Pad Inc.</p>
                <p>3030 N Rocky Point Dr W Suite 150</p>
                <p>Tampa, FL 33607</p>




                <p>Your written notification must include (1) your name, (2) your address, and (3) a clear statement that you do not wish to resolve disputes with Sprowtt Launch Pad Inc. through arbitration. Your decision to opt-out of this Arbitration Provision will have no adverse effect on your relationship with Sprowtt Launch Pad Inc. Any opt-out request received after the Opt-Out Deadline will not be valid and you must pursue your Dispute in arbitration or small claims court.</p>
                <p>Arbitration Award. The arbitrator may award on an individual basis any relief that would be available pursuant to applicable law and will not have the power to award relief to, against or for the benefit of any person who is not a party to the proceeding. The arbitrator’s award will be in writing, will be signed by the arbitrator, and will include a determination of all the questions submitted to the arbitrator the decision of which is necessary in order to determine the controversy. Such award by the arbitrator will be final and binding on the parties, except for any right of appeal provided by law, and may be entered in any court having jurisdiction over the parties for purposes of enforcement.</p>
                <p>Location of Arbitration. You may initiate arbitration in the federal judicial district that includes your address that you provide in your written notification of Pre-Arbitration Dispute Resolution. In the event that Sprowtt Launch Pad Inc. initiates an arbitration, it may only do so in the federal judicial district that includes your address that you provide in your written notification of Pre-Arbitration Dispute Resolution or the billing address for your account.</p>
                <p>Payment of Arbitration Fees and Costs. Sprowtt Launch Pad Inc. will pay all arbitration filing fees and arbitrator’s costs and expenses upon your written request given prior to the commencement of the arbitration. You are responsible for all additional fees and costs that you incur in the arbitration, including, but not limited to, attorneys or expert witnesses. Fees and costs may be awarded by the arbitrator as provided pursuant to applicable law. In addition to any rights to recover fees and costs under applicable law, if you provide notice and negotiate in good faith with Sprowtt Launch Pad Inc. as provided in the “Pre-Arbitration Dispute Resolution” Section and the arbitrator concludes that you are the prevailing party in the arbitration, you will be entitled to recover from Sprowtt Launch Pad Inc. your actual and reasonable attorney’s fees and costs as determined by the arbitrator.</p>
                <p>Class Action Waiver. You and Sprowtt Launch Pad Inc. waive any right to assert any claim against one another by means of any class action or representative action, whether as a class representative or as a member of a class. If, notwithstanding the foregoing waiver, a court or law permits a party to this Agreement to participate in a class or representative action, then the prevailing party will not be entitled to recover attorneys’ fees or costs associated with pursuing the class or representative action, and the party who initiates or participates as a member of the class will not submit a claim or otherwise participate in any recovery secured through the class or representative action.</p>
                <p>Limitation of Procedural Rights. You understand and agree that, by entering into this Arbitration Agreement, you and Sprowtt Launch Pad Inc. are each agreeing to arbitration instead of the right to a trial before a judge or jury in a public court. In the absence of this Arbitration Agreement, you and Sprowtt Launch Pad Inc. might otherwise have had a right or opportunity to bring Disputes in a court, before a judge or jury, and/or to participate or be represented in a case filed in court by others (including class actions). You give up those rights. Other rights that you would have if you went to court, such as the right to appeal and to certain types of discovery, may be more limited in arbitration. The right to appellate review of an arbitrator’s decision is much more limited than in court, and in general an arbitrator’s decision may not be appealed for errors of fact or law.</p>
                <p>Severability. If any clause within this Arbitration Agreement (other than the Class Action Waiver clause above) is found to be illegal or unenforceable, that clause will be severed from this Arbitration Agreement, and the remainder of this Arbitration Agreement will be given full force and effect. If the Class Action Waiver clause is found to be illegal or unenforceable, then this entire Arbitration Agreement will be unenforceable, and the Dispute will be decided by a court.</p>
                <p>Continuation. This Arbitration Agreement will survive the termination of your contract with Sprowtt Launch Pad Inc. and your use of the Services.</p>


                <p>Anti-Corruption, Export and Sanctions Compliance. With respect to these Terms, you represent, warrant, and covenant that you:</p>
                <p>have not and will not violate, or cause any party to be in violation of, any applicable anti-bribery or anti-corruption law (including, but not limited to, the U.S. Foreign Corrupt Practices Act of 1977, as amended, the U.S. domestic bribery statute in 18 U.S.C. 201, the U.S. Travel Act, or the UK Bribery Act 2010), anti-kickback laws, anti-money laundering and anti-terrorist financing laws, sanctions, embargoes, export controls, import controls, anti-fraud laws, or any other applicable law, regulation, or order (collectively, “Applicable Laws”);</p>
                <p>have not and will not use or apply the Services or the Website in violation of Applicable Laws;</p>
                <p>have not and will not with a corrupt, improper, or illegal intention directly or indirectly (through third parties) pay, provide, promise, offer, authorize, solicit, or accept any money, gift, hospitality, entertainment, favor, financial advantage, or other thing of value to or from any individual, organization, political party, or entity whether in the public or private sector in any country in order to obtain, retain, or direct regulatory approvals, licenses, permits, business, contracts, investments, sales, tax or duty assessments, import or export clearances, foreign exchange clearances, or other advantages;</p>
                <p>shall cause all of your employees, officers, directors, agents, contractors, vendors, and partners (collectively, “Relevant Parties”) to comply with all of the terms contained in this Anti-Corruption, Export and Sanctions Compliance Section;</p>
                <p>are not, and will ensure that your Relevant Parties and customers are not, (a) nationals, residents, agents or representatives of Iran, Cuba, North Korea, Syria, the Crimea Region of Ukraine, or any other region subject to comprehensive U.S. sanctions; (b) on the List of Specially Designated Nationals & Blocked Persons, the Sectoral Sanctions Identifications (SSI) List, or Foreign Sanctions Evaders List maintained by the Office of Foreign Assets Control of the U.S. Department of the Treasury, or any other applicable list of sanctioned, embargoed, blocked, criminal, or debarred persons maintained by any U.S. or non-U.S. government, the European Union, Interpol, the United Nations, the World Bank, or any other public international organization (each such list, a “Sanctions List”); (c) an entity that is 50% or more owned, individually or in the aggregate, directly or indirectly, by, is controlled by (including without limitation by virtue of such person being a director or owning voting shares or interests), or acts, directly or indirectly, for or on behalf of, any person or entity on a Sanctions List; or (d) otherwise the target of any sanctions, suspensions, embargoes or debarment by the U.S. government or any other government or public international organization;</p>
                <p>shall secure all necessary export/sanctions licenses or authorizations to the extent applicable and necessary;</p>
                <p>shall implement an effective, risk-based compliance program and necessary internal controls (including, but not limited to, conducting sanctions screenings of your Relevant Parties and customers) to ensure compliance with Applicable Laws and this Anti-Corruption, Export and Sanctions Compliance Section;</p>
                <p>shall review and adhere to Sprowtt Launch Pad Inc.’s Company Associate Compliance Guide if provided by Sprowtt Launch Pad Inc.; and</p>
                <p>shall reasonably cooperate with Sprowtt Launch Pad Inc. to (a) ensure compliance with sanctions, embargoes, and other Applicable Laws and/or (b) review and remediate actual or potential violations of sanctions or other Applicable Laws, including, but not limited to, suspending or terminating the supply of products or services to customers or other persons that appear on a Sanctions List or are otherwise the target of sanctions and other similar restrictions.</p>
                <p>A violation of the foregoing representations, warranties, or covenants will constitute a material breach of these Terms, and, in the event of such a violation, Sprowtt Launch Pad Inc. may, at its sole option, terminate this Agreement for cause and without further liability or obligation on the part of Sprowtt Launch Pad Inc.. Any such breach will entitle Sprowtt Launch Pad Inc. to seek to be indemnified by you and/or obtain injunctive and other equitable relief, in addition to any other remedies which may be available under Applicable Laws.</p>


                <p>CGA Terms.</p>
                <p>Modifications. Sprowtt Launch Pad Inc. reserves the right, in its discretion, to change, modify, add to, or remove portions of the Terms (collectively, “Changes”), at any time. Sprowtt Launch Pad Inc. will notify you of Changes by sending an email to the address identified in your Account or by posting a revised version of the Terms incorporating the Changes to its Website. Your continued use of the Website or Services following notice of the Changes (or posting of the Terms incorporating the Changes in the event your email address is no longer valid, is blocked, or is otherwise not able to receive the notice) will mean that you accept and agree to the Changes. Such Changes will apply prospectively beginning on the date the Changes are posted to the Website.</p>
                <p>Term; Termination.</p>
                <p>Term. The Services will be provided to you for the duration of your Services subscription or Order Form, unless earlier cancelled by you or terminated by Sprowtt Launch Pad Inc.. You may cancel your Services subscription at any time. These Terms will automatically terminate upon the cancellation of all of your Services subscriptions. Sprowtt Launch Pad Inc. may terminate these Terms or your Services subscription(s) at any time, with or without cause, upon written notice. Sprowtt Launch Pad Inc. will have no liability to you or any third party because of such termination. Termination of these Terms will terminate all of your Services subscriptions.</p>
                <p>Effect of Termination.Upon termination of these Terms by either party for any reason, or cancellation or expiration of your Services subscriptions: (i) Sprowtt Launch Pad Inc. will cease providing the Services; (ii) you will not be entitled to any refunds of any subscription or usage fees, or any other fees, pro rata or otherwise; (iii) any fees you owe to Sprowtt Launch Pad Inc. will immediately become due and payable in full; and (iv) Sprowtt Launch Pad Inc. may delete your archived data within 30 days. All sections of the Terms that expressly provide for survival, or by their nature should survive, will survive termination of the Terms, including, without limitation, confidentiality, indemnification, warranty disclaimers, and limitations of liability.</p>
                <p>Limitations of Liability.</p>
                <p>Excluded Damages and Theories. SPROWTT LAUNCH PAD INC. AND ITS SUPPLIERS AND AFFILIATES ASSUME NO RESPONSIBILITY WITH RESPECT TO YOUR OR YOUR USER’S USE OF THE WEBSITE, SOFTWARE, OR SERVICES AND WILL NOT BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, PUNITIVE, EXTRAORDINARY, EXEMPLARY OR SPECIAL DAMAGES, INCLUDING, WITHOUT LIMITATION, LOSS OF USE, BUSINESS INTERRUPTIONS, LOSS OF DATA, LOSS OF PROFITS, AND LOST REVENUE, WHETHER SUCH DAMAGES ARE ALLEGED IN TORT, CONTRACT OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT SPROWTT LAUNCH PAD INC. IS AWARE OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                <p>Aggregate Liability. SPROWTT LAUNCH PAD INC. AND ITS SUPPLIERS AND AFFILIATES WILL IN NO EVENT BE LIABLE IN AGGREGATE FOR MORE THAN THE TOTAL FEES ACTUALLY RECEIVED BY SPROWTT LAUNCH PAD INC. FROM YOU FOR THE SERVICES DURING THE 12-MONTH PERIOD BEFORE THE CLAIM OR CAUSE OF ACTION AROSE.</p>
                <p>Multiple Claims; Time Limits. MULTIPLE CLAIMS WILL NOT EXPAND THIS LIMITATION. ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE WEBSITE, SOFTWARE, OR SERVICES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CLAIM OR CAUSE OF ACTION ACCRUES, OTHERWISE SUCH CLAIM AND CAUSE OF ACTION WILL BE PERMANENTLY BARRED.</p>
                <p>Jurisdictions; Limitations. SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION AND/OR LIMITATION OF CONSEQUENTIAL, INCIDENTAL, SPECIAL OR OTHER DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH EVENT, THE LIABILITY OF SPROWTT LAUNCH PAD INC. AND ITS SUPPLIERS AND AFFILIATES FOR SUCH DAMAGES WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. THIS LIMITATIONS OF LIABILITY SECTION WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THESE TERMS.</p>
                <p>Disclaimers.</p>
                <p>General. YOUR USE OF THE WEBSITE, SOFTWARE, AND SERVICES WILL BE AT YOUR OWN RISK AND ARE PROVIDED “AS IS”, “AS AVAILABLE” AND “WITH ALL FAULTS”. SPROWTT LAUNCH PAD INC. AND ITS SUPPLIERS AND AFFILIATES DISCLAIM ALL WARRANTIES, CONDITIONS, REPRESENTATIONS, WHETHER STATUTORY, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES, CONDITIONS AND REPRESENTATIONS OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
                <p>Specific. SPROWTT LAUNCH PAD INC. MAKES NO WARRANTIES, CONDITIONS OR REPRESENTATIONS ABOUT (i) THE ABILITY OF THE WEBSITE, SERVICES, OR SOFTWARE TO PERFORM WITHOUT LIMITATION OR RESTRICTION IN ANY GIVEN ENVIRONMENT, (ii) THE ACCURACY, COMPLETENESS, OR CONTENT OF THE WEBSITE, SERVICES, OR SOFTWARE, (iii) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY LINKED SITES (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE), AND/OR (iv) THIRD-PARTY PRODUCTS, AND SPROWTT LAUNCH PAD INC. ASSUMES NO LIABILITY OR RESPONSIBILITY THEREWITH.</p>
                <p>Third-Party Products. THE REFERENCE TO, OR AVAILABILITY OF, THIRD-PARTY PRODUCTS IN CONNECTION WITH THE SERVICES OR WEBSITE DOES NOT CONSTITUTE, AND WILL NOT BE CONSTRUED AS CONSTITUTING, AN ENDORSEMENT, AUTHORIZATION, SPONSORSHIP, OR AFFILIATION BY OR WITH SPROWTT LAUNCH PAD INC. WITH RESPECT TO SUCH THIRD-PARTY PRODUCTS.</p>
                <p>Legal, Tax, Financial, Other Communications. NO ORAL OR WRITTEN INFORMATION OR ADVICE OR COMMUNICATIONS PROVIDED BY SPROWTT LAUNCH PAD INC. OR ANY OF ITS EMPLOYEES WILL CONSTITUTE PERSONAL, LEGAL, TAX OR FINANCIAL ADVICE OR CREATE A WARRANTY, CONDITION OR REPRESENTATION OF ANY KIND.
                Jurisdictions; Limitations. THESE DISCLAIMERS APPLY TO THE FULLEST EXTENT PERMITTED BY LAW AND WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THESE TERMS. SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION AND/OR LIMITATION OF IMPLIED REPRESENTATIONS, CONDITIONS OR WARRANTIES, OR ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH EVENT, SPROWTT LAUNCH PAD INC.’S WARRANTIES, CONDITIONS AND REPRESENTATIONS WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW IN SUCH JURISDICTION.</p>
                <p>Confidentiality.</p>
                <p>Definition. “Confidential Information” means the business, technical and financial information disclosed to one party (the “Receiving Party”) by the other party (the “Disclosing Party”) pursuant to these Terms and includes all information marked by the Disclosing Party as confidential and any other information, whether written or oral, that the Receiving Party should reasonably understand is confidential to the Disclosing Party.</p>
                <p>Obligations. The Receiving Party will: (i) hold the Confidential Information of the Disclosing Party in trust and confidence and not disclose or release the Confidential Information to any third party except as provided herein; and (ii) not use the Confidential Information for any purpose except for the purposes described in these Terms. The disclosure of Confidential Information pursuant to these Terms is not intended in any way to transfer or grant any right, title or interest in or to such Confidential Information to the Receiving Party unless otherwise expressly indicated by the Disclosing Party in writing.</p>
                <p>Standard of Care. The standard of care imposed on each party pursuant to this Section will be the same degree of care as it uses to avoid the unauthorized use, disclosure, or dissemination of its own Confidential Information of a similar nature, but not less than a commercially reasonable degree of care.</p>
                <p>Limitation. Each party will disclose the Confidential Information of the other party only to those of its employees, consultants and contractors (“Personnel”) who have agreed, either as a condition of employment, representation or in a written agreement, to be bound by terms and conditions substantially as protective as the confidentiality terms and conditions applicable to the Receiving Party under this Section.</p>
                <p>Exclusions. Confidential Information excludes information that is (i) rightfully in the Receiving Party’s possession without obligation of confidentiality prior to receipt from the Disclosing Party, (i a matter of public knowledge through no fault of the Receiving Party, (iii) rightfully furnished to the Receiving Party by a third party without restriction on disclosure or use; or (iv) independently developed by the Receiving Party without use of or reference to the Disclosing Party's Confidential Information.</p>
                <p>Requests for Confidential Information. A Receiving Party may disclose Confidential Information pursuant to a valid court order or order of an authorized government agency, provided that (if not legally prohibited) the Receiving Party has given the Disclosing Party prompt notice so that the Disclosing Party will have an opportunity to defend, limit or protect against such disclosure and the Receiving Party limits such disclosure to only that Confidential Information subject to the applicable order.</p>
                <p>Survival. The terms of this Section will survive for as long as the Confidential Information remains confidential.</p>
                <p>Backup Storage. For its own operational efficiencies and purposes, Sprowtt Launch Pad Inc. from time to time back up data on its servers but is under no obligation or duty to you to do so under these Terms or otherwise. IT IS SOLELY YOUR DUTY AND RESPONSIBILITY TO BACKUP SEPARATELY YOUR FILES AND DATA THAT MAY RESIDE ON SPROWTT LAUNCH PAD INC. SERVERS. UNDER NO CIRCUMSTANCES WILL SPROWTT LAUNCH PAD INC. BE LIABLE TO YOU, YOUR USERS, OR ANY THIRD PARTY FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, FOR LOSS OF FILES AND/OR DATA ON ANY SPROWTT LAUNCH PAD INC. SERVER.</p>
                <p>No Assignment by You. You may not assign your rights or obligations under these Terms without the prior written consent of Sprowtt Launch Pad Inc., which Sprowtt Launch Pad Inc. may refuse in its sole discretion. Any attempted assignment without prior written consent from Sprowtt Launch Pad Inc. will be deemed null and void. Sprowtt Launch Pad Inc. may assign its rights and/or obligations under these Terms at any time. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their respective successors and permitted assigns.</p>
                <p>Notices.</p>
                <p>You consent to receive electronically any communications from Sprowtt Launch Pad Inc. We may communicate with you through the email address specified in your account or by posting notices on the Website. You agree that all agreements, notices, disclosures and other communications that are provided to you electronically satisfy any requirement that such communications be in writing. All notices from us intended for receipt by you shall be deemed delivered and effective when sent to the email address you provide to us.</p>
                <p>Notices to Sprowtt Launch Pad Inc. must be sent to: trustandsafety@Sprowtt Launch Pad Inc..com</p>
                <p>Entire Agreement. These Terms are the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications, and other understandings relating to the subject matter of these Terms, and any modifications must be in a writing signed by both parties, except as otherwise provided herein.</p>


                <p>Miscellaneous.</p>
                <p>Governing Law; Jurisdiction. The law that will govern the validity and construction of these Terms and apply in any dispute or lawsuit arising out of or relating to these Terms is as set forth in table in the Contracting Entity Section above. You hereby consent to and waive all defenses of lack of personal jurisdiction and forum non conveniens with respect to, the jurisdiction and venue of the federal and state courts located in Hillsborough County, Florida (USA). The United Nations Convention on Contracts for the International Sale of Goods will not apply to these Terms and is hereby expressly excluded.</p>
                <p>Severability. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect and enforceable.</p>
                <p>Waiver. No waiver of any provision of these Terms, nor consent by Sprowtt Launch Pad Inc. to the breach of or departure from any provision of these Terms, will in any event be binding on or effective against Sprowtt Launch Pad Inc. unless it be in writing and signed by a duly authorized representative of Sprowtt Launch Pad Inc., and then such waiver will be effective only in the specific instance and for the specific purpose for which given.</p>
                <p>Section Headings. The section headings and titles in these Terms are for convenience only and have no legal or contractual effect. These Terms will be interpreted without application of any strict construction in favor of or against you or Sprowtt Launch Pad Inc.</p>
                <p>Independent Contractors. No agency, partnership, joint venture or employment relationship is created by these Terms or your use of the Services, and you do not have any authority of any kind to bind Sprowtt Launch Pad Inc. in any respect whatsoever.</p>
                <p>Force Majeure. Sprowtt Launch Pad Inc. will have no liability to you, your users, or any third party for any failure by Sprowtt Launch Pad Inc. to perform its obligations under these Terms in the event that such non-performance arises as a result of the occurrence of an event beyond the reasonable control of Sprowtt Launch Pad Inc., including, without limitation, an act of war or terrorism, natural disaster, failure of electricity supply, riot, civil disorder, or civil commotion or other force majeure event.</p>
                <p>Third-Party Service Integration. Certain Third-Party Products may be integrated with the Services. Sprowtt Launch Pad Inc. may, in its discretion and without liability to you, decide to no longer support such integration and migrate your Services subscription to a different integration.</p>
                <p>Hosting Services. Sprowtt Launch Pad Inc. has entered into arrangements with one or more third parties for hosting services that are essential to the Services, incorporated within the Services and without which the Services could not be provided to you.</p>
                <p>Virtual Machine Commands and Runtime Engines. Use of Sprowtt Launch Pad Inc.’s ecommerce website design platform to author webpages (or portions thereof) that are displayed through the use of virtual machine commands or a runtime engine is prohibited.</p>


            </div>
        </div>
    </div>
</section>



@endsection